import { ProjectDeployment } from '../types';

export const INITIAL_DEPLOYMENTS: ProjectDeployment[] = [
  {
    id: 'dep-front',
    name: 'front',
    appFramework: 'React SPA',
    target: 'front',
    status: 'ready',
    previewUrl: 'https://7camz-front-preview.edge.app',
    updatedAt: 'April 14, 2022 at 5:10PM (UTC)',
    branch: 'main',
    commitHash: '7c8a91f',
    commitMessage: 'feat(studio): sync 4K cinematic assets and visual media portal',
    assetsCount: 4,
    environment: 'production',
    deployDuration: '32s',
    logs: [
      '[17:09:28] Vercel CLI v34.1.2 — Ready for Git deployment',
      '[17:09:30] Cloning repository git@github.com:7camz/studio-monorepo.git (branch: main)',
      '[17:09:32] Analyzing monorepo workspace package: "front"',
      '[17:09:35] Installing dependencies with pnpm...',
      '[17:09:44] Running build command "vite build"...',
      '[17:09:51] ✓ Compiled 1,678 modules into 4 bundles',
      '[17:09:55] Optimizing WebP/AVIF images and procedural audio engine...',
      '[17:10:00] Generated static pages & client edge routes',
      '[17:10:01] Assigning global CDN alias: 7camz-front-preview.edge.app',
      '[17:10:02] ✅ Deployment completed in 32s. Edge network cached globally in 18 regions.',
    ],
  },
  {
    id: 'dep-next-site',
    name: 'next-site',
    appFramework: 'Next.js',
    target: 'next-site',
    status: 'ready',
    previewUrl: 'https://7camz-next-site.edge.app',
    updatedAt: 'April 14, 2022 at 5:09PM (UTC)',
    branch: 'feature/cinematic-timeline',
    commitHash: '3e41b2d',
    commitMessage: 'feat(video): add 60fps canvas render engine & subtitles',
    assetsCount: 6,
    environment: 'preview',
    deployDuration: '44s',
    logs: [
      '[17:08:25] Triggered by GitHub commit 3e41b2d on feature/cinematic-timeline',
      '[17:08:29] Next.js 14.2.0 App Router detected',
      '[17:08:38] Collecting static generation pages and SSR server functions...',
      '[17:08:48] Prerendered 12 static HTML routes for client preview showreel',
      '[17:08:55] CDN cache purge completed across edge regions: iad1, lhr1, fra1, hnd1',
      '[17:09:00] ✅ Ready at https://7camz-next-site.edge.app',
    ],
  },
  {
    id: 'dep-svelte-app',
    name: 'svelte-app',
    appFramework: 'SvelteKit',
    target: 'svelte-app',
    status: 'building',
    previewUrl: 'https://7camz-svelte-app-building.edge.app',
    updatedAt: 'April 14, 2022 at 5:08PM (UTC)',
    branch: 'chore/audio-sequencer',
    commitHash: '9a02d84',
    commitMessage: 'refactor(synth): 16-step sequencer audio loop with solo/mute stems',
    assetsCount: 3,
    environment: 'preview',
    deployDuration: 'In progress...',
    logs: [
      '[17:08:02] Build triggered for monorepo workspace "svelte-app"',
      '[17:08:05] Running SvelteKit adapter-auto build...',
      '[17:08:12] Compiling audio worklets and procedural synthesizers...',
      '[17:08:18] Optimizing Web Audio API pipeline for zero latency...',
      '[17:08:22] Packaging client audio bundles (98% complete)...',
    ],
  },
];
