import { MediaItem, VoicePreset, CreditPlan, StemChannel } from '../types';
import {
  heroMultimediaStudio,
  samplePortraitCyber,
  sampleCinematicLandscape,
  sampleAudioVisualizer,
} from '../assets';

export const INITIAL_MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'med-01',
    title: 'Neon Odyssey 2099',
    type: 'image',
    url: sampleCinematicLandscape,
    thumbnail: sampleCinematicLandscape,
    prompt: 'Cinematic wide-angle view of a futuristic neon city canyon with flying vehicles and glowing architectural glass towers at dusk, golden hour rim reflections, 8k aesthetic',
    createdAt: '12 minutes ago',
    tags: ['Sci-Fi', 'Metropolis', '8K', 'Lighting'],
    dimensions: '3840 x 2160',
    format: 'PNG',
    creditsUsed: 15,
  },
  {
    id: 'med-02',
    title: 'Holographic Soundscape',
    type: 'music',
    url: sampleAudioVisualizer,
    thumbnail: sampleAudioVisualizer,
    prompt: 'Surreal cosmic soundwave album artwork, vibrant fluid soundwaves intertwining with a glowing celestial sphere',
    createdAt: '38 minutes ago',
    tags: ['Synthwave', '118 BPM', 'Atmospheric', 'Stereo Stems'],
    duration: '02:45',
    format: 'WAV 24-bit',
    creditsUsed: 25,
  },
  {
    id: 'med-03',
    title: 'Synthetic Empathy v2',
    type: 'image',
    url: samplePortraitCyber,
    thumbnail: samplePortraitCyber,
    prompt: 'Cinematic portrait of a futuristic digital creator wearing studio monitor headphones, subtle iridescent holographic reflection, soft rim lighting',
    createdAt: '1 hour ago',
    tags: ['Cyberpunk', 'Character', 'Studio Light', 'Portrait'],
    dimensions: '2048 x 2560',
    format: 'PNG',
    creditsUsed: 12,
  },
  {
    id: 'med-04',
    title: 'Cyber City Flythrough',
    type: 'video',
    url: sampleCinematicLandscape,
    thumbnail: sampleCinematicLandscape,
    prompt: 'Continuous aerial dolly push through neon skyscraper canyons, atmospheric fog, rain droplets on camera lens, 60fps',
    createdAt: '2 hours ago',
    tags: ['Motion 4K', 'Dolly Push', '60 FPS', 'HDR'],
    duration: '00:15',
    dimensions: '3840 x 2160',
    format: 'ProRes 422',
    creditsUsed: 40,
  },
  {
    id: 'med-05',
    title: 'Commercial Director Voiceover',
    type: 'voice',
    url: '',
    thumbnail: '',
    prompt: 'Deep cinematic narrator delivering launch announcement for the next-generation spatial computing OS with calm authority',
    createdAt: '3 hours ago',
    tags: ['Voice Clone', 'Deep Narrator', 'Pacing 1.0x', 'Neutral EQ'],
    duration: '00:42',
    format: 'FLAC 48kHz',
    creditsUsed: 10,
  },
];

export const VOICE_PRESETS: VoicePreset[] = [
  {
    id: 'voice-atlas',
    name: 'Atlas',
    role: 'Deep Cinematic Narrator',
    gender: 'male',
    accent: 'North American Baritone',
    sampleAudioText: 'In a world shaped by imagination, 7Camz Studio gives you absolute power over light, movement, and sound.',
    color: '#06b6d4',
  },
  {
    id: 'voice-nova',
    name: 'Nova',
    role: 'Energetic Tech Host',
    gender: 'female',
    accent: 'Contemporary Neutral',
    sampleAudioText: 'Welcome back creators! Today we are testing the brand new neural video keyframing engine in real time.',
    color: '#3b82f6',
  },
  {
    id: 'voice-lyra',
    name: 'Lyra',
    role: 'Gentle ASMR & Meditation',
    gender: 'female',
    accent: 'Soft Ambient English',
    sampleAudioText: 'Breathe in slowly. Let the soundscape wash over your senses and inspire your next masterpiece.',
    color: '#10b981',
  },
  {
    id: 'voice-vance',
    name: 'Vance',
    role: 'Commercial Broadcast Anchor',
    gender: 'male',
    accent: 'Global English Executive',
    sampleAudioText: 'Engineered for high-throughput studios, reducing production turnaround from days to seconds.',
    color: '#f59e0b',
  },
  {
    id: 'voice-echo',
    name: 'Echo-07',
    role: 'Cyber Synthesizer Bot',
    gender: 'neural',
    accent: 'Futuristic Robotic Vocoder',
    sampleAudioText: 'Audio stems calibrated. Quantum neural rendering initialized across all 4 production tracks.',
    color: '#8b5cf6',
  },
  {
    id: 'voice-maya',
    name: 'Maya',
    role: 'Expressive Documentary Voice',
    gender: 'female',
    accent: 'Warm British RP',
    sampleAudioText: 'Across the shifting skyline, centuries of architecture stood illuminated by modern brilliance.',
    color: '#ec4899',
  },
];

export const CREDIT_PLANS: CreditPlan[] = [
  {
    id: 'starter',
    name: 'Creator Starter',
    tagline: 'Ideal for independent artists and content makers',
    credits: 500,
    price: 19,
    costPerCredit: '$0.038 / credit',
    features: [
      '500 Multi-modal Studio credits',
      'Ultra HD image generation & editing',
      'Up to 1080p 60fps video renders',
      'Standard TTS & voice synthesis',
      'Step beatmaker & stem export (MP3)',
      '14-day cloud asset vault storage',
    ],
  },
  {
    id: 'pro',
    name: 'Studio Pro',
    tagline: 'Best value for active creators & commercial editors',
    credits: 2500,
    price: 49,
    popular: true,
    costPerCredit: '$0.019 / credit',
    features: [
      '2,500 Multi-modal Studio credits',
      '4K Ultra upscale with inpainting brush',
      '60fps video with camera dynamics & motion paths',
      'Full voice cloning & emotional pitch control',
      '16-step sequencer + lossless WAV 24-bit stems',
      'LiveCam OBS virtual overlays & LUT filters',
      'Unlimited cloud vault with batch download',
    ],
  },
  {
    id: 'agency',
    name: 'Agency Master',
    tagline: 'Maximum throughput for creative studios & teams',
    credits: 10000,
    price: 149,
    costPerCredit: '$0.014 / credit',
    features: [
      '10,000 High-priority credits',
      'ProRes 422 video timeline master export',
      'Zero-latency GPU rendering pipeline',
      'Custom brand voice training & audio stems',
      'Collaborative team workspace & OBS feeds',
      'Dedicated support & commercial license',
      'API direct access for batch generation',
    ],
  },
];

export const INITIAL_STEMS: StemChannel[] = [
  { id: 'stem-vocals', name: 'Vocals / Acapella', volume: 85, isMuted: false, isSolo: false, pan: 0, color: '#06b6d4' },
  { id: 'stem-drums', name: 'Drums & Percussion', volume: 92, isMuted: false, isSolo: false, pan: -10, color: '#3b82f6' },
  { id: 'stem-bass', name: '808 Sub & Bassline', volume: 88, isMuted: false, isSolo: false, pan: 5, color: '#8b5cf6' },
  { id: 'stem-synths', name: 'Melodies & Atmosphere', volume: 75, isMuted: false, isSolo: false, pan: 15, color: '#ec4899' },
];
